# fleet-config/fleet.yaml
apiVersion: fleet.cattle.io/v1alpha1
kind: Bundle
metadata:
  name: demo-app
spec:
  resources:
  - name: app-manifests
    content: |
      {{ .Files.Get "../app/deployment.yaml" }}
  targets:
  - name: local
    clusterSelector:
      matchLabels:
        management.cattle.io/cluster-display-name: local
